title: Help Center
description: Official knowledge base for getinside Retail Media operations.
url: https://getinside-ops.github.io/handbook
baseurl: /handbook

# Thème officiel
remote_theme: just-the-docs/just-the-docs

# Schéma de couleur par défaut (Light)
color_scheme: light

# Navigation & Recherche
search_enabled: true
search_tokenizer_separator: /[\s/]+/

# Liens utiles
aux_links:
  "Accès SaaS":
    - "https://app.getinside.media/"
  "Site Web":
    - "https://getinside.fr/"

# Footer
footer_content: "Copyright &copy; 2025 getinside."

# Désactivation globale du sommaire pour éviter les bugs d'affichage
defaults:
  - scope:
      path: ""
    values:
      toc: false