title: Handbook
description: Le mode d'emploi getinside
url: "https://getinside-ops.github.io"

# Le ThÃ¨me
remote_theme: pmarsceill/just-the-docs

# 1. Branding (Logo)
#logo: "/assets/images/logo-getinside.png"
favicon_ico: "/assets/images/favicon.ico"

# 2. Mode Sombre (Automatique)
color_scheme: nil

# 3. Recherche
search_enabled: true
search:
  heading_level: 2
  previews: 3

# 4. Switch Langue (En haut Ã  droite)
aux_links:
  "ðŸ‡¬ðŸ‡§ English":
    - "/docs/en"
  "ðŸ‡«ðŸ‡· FranÃ§ais":
    - "/docs/fr"

# Plugins techniques
plugins:
  - jekyll-seo-tag
# -----------------------------------------------------------------------------
# Valeurs par dÃ©faut pour toutes les pages
# -----------------------------------------------------------------------------
defaults:
  - scope:
      path: ""
    values:
      toc: false

# Footer du menu de gauche
footer_content: " "