title: Help Center
description: Official knowledge base for getinside Retail Media operations.
url: https://getinside-ops.github.io/handbook
baseurl: /handbook

# Le thème
remote_theme: just-the-docs/just-the-docs

# On désactive le schéma de couleur par défaut pour laisser la main à notre SCSS
color_scheme: nil

# Chargement des polices UNIQUEMENT (Pas de fichier CSS ici !)
head_members:
  - <link rel="preconnect" href="https://fonts.googleapis.com">
  - <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  - <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Public+Sans:wght@300;400;700&family=Space+Grotesk:wght@500;700&display=swap" rel="stylesheet">

# Navigation & Recherche
search_enabled: true
search_tokenizer_separator: /[\s/]+/

aux_links:
  "Accès SaaS":
    - "https://app.getinside.media/"
  "Site Web":
    - "https://getinside.fr/"

footer_content: "Copyright &copy; 2025 getinside."

defaults:
  - scope:
      path: ""
    values:
      toc: false