# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Help Center
description: Official knowledge base for getinside Retail Media operations.
url: https://getinside-ops.github.io/handbook
baseurl: /handbook

# Le thème officiel
remote_theme: just-the-docs/just-the-docs

# --- MODIFICATION ICI ---
# On appelle notre fichier _sass/color_schemes/getinside.scss
color_scheme: getinside

# Navigation & Recherche
search_enabled: true
search_tokenizer_separator: /[\s/]+/

# Liens
aux_links:
  "Accès SaaS":
    - "https://app.getinside.media/"
  "Site Web":
    - "https://getinside.fr/"

# Footer
footer_content: "Copyright &copy; 2025 getinside."

# Defaults
defaults:
  - scope:
      path: ""
    values:
      toc: false