title: Help Center
description: Official knowledge base for getinside Retail Media operations.
url: https://getinside-ops.github.io/handbook
baseurl: /handbook

remote_theme: just-the-docs/just-the-docs

# On appelle le fichier _sass/color_schemes/getinside.scss
color_scheme: getinside

search_enabled: true
search_tokenizer_separator: /[\s/]+/

aux_links:
  "Acc√®s SaaS":
    - "https://app.getinside.media/"
  "Site Web":
    - "https://getinside.fr/"

footer_content: "Copyright &copy; 2025 getinside."

defaults:
  - scope:
      path: ""
    values:
      toc: false