# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Handbook
description: Official knowledge base for getinside Retail Media operations.
url: https://getinside-ops.github.io/handbook
baseurl: /handbook

# Le thème officiel
remote_theme: just-the-docs/just-the-docs
mermaid:
  enabled: true

# Schéma de couleur par défaut (Light = Violet)
color_scheme: light

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from


# -----------------------------------------------------------------------------
# Navigation & Recherche
# -----------------------------------------------------------------------------

search_enabled: true
search_tokenizer_separator: /[\s/]+/

# Liens en haut à droite
aux_links_new_tab: true
aux_links:
  "Accès SaaS":
    - "https://app.getinside.media/"
  "Site Web":
    - "https://getinside.fr/"

    

# -----------------------------------------------------------------------------
# Footer
# -----------------------------------------------------------------------------

footer_content: "Copyright &copy; 2025 getinside."